// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhifdfvqapnebfiifpsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloaWZkZnZxYXBuZWJmaWlmcHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjIxNTcsImV4cCI6MjA3MTI5ODE1N30.zVJdUjDg9TJNzza28fJ88u78a5ocD_mowbcKE9CGOFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});